Add ssh key for Damian Nadales (dnadales).
input-output-hk/ops-lib pull request #42
Opened 2020-10-07 10:10 UTC by dnadales

2020-10-07 10:12 UTC, dnadales commented
I also aligned the `=` signs in `csl-developers`, so it might be helpful to review this asking github to ignore whitespaces in the diff.

2020-10-07 10:13 UTC, dnadales commented
@iohk-devops, I'm able to merge this pull request. I do not know if I should have this permission.

2020-10-08 16:13 UTC, disassembler requested changes

2020-10-08 16:13 UTC, disassembler commented on overlays/ssh-keys.nix
> +    dnadales       = [ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC79R4WdKcB34PamcmHkEnafstXd8KUMhgreye8txe99LTs0HKwbSrDlIQ47zu6o4TdU8MbjynGRfEuApy8IBRO9swjj+K9X0vcyWIXgWwIfFVqGyqLcdbzF2PAHzS4TPHzIfWMlaT
missing `;`

2020-10-08 16:18 UTC, disassembler commented
> @iohk-devops, I'm able to merge this pull request. I do not know if I should have this permission.

I've added CODEOWNERS and branch protection. Thanks for the heads up!

2020-10-08 16:19 UTC, disassembler requested changes

2020-10-08 16:19 UTC, disassembler commented on overlays/ssh-keys.nix
> +    dnadales       = [ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC79R4WdKcB34PamcmHkEnafstXd8KUMhgreye8txe99LTs0HKwbSrDlIQ47zu6o4TdU8MbjynGRfEuApy8IBRO9swjj+K9X0vcyWIXgWwIfFVqGyqLcdbzF2PAHzS4TPHzIfWMlaT
```suggestion
    dnadales       = [ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC79R4WdKcB34PamcmHkEnafstXd8KUMhgreye8txe99LTs0HKwbSrDlIQ47zu6o4TdU8MbjynGRfEuApy8IBRO9swjj+K9X0vcyWIXgWwIfFVqGyqLcdbzF2PAHzS4TPHzIfWMlaT9cKZ4a6e60xwL6fJwfFyWzxD6vGF5KuVnOGEoHMvVao5TV/bcO1lJ3WagFdw0MpVoYjwM3km/QwZiAOAl28HlVTe+j6vN1Io6EaTnRMEXppB4rhQnBFCdB4xmkxCFMZwKwXuUEfP4C+ob6j49PCg5694Ig+7y4QOZo9Dc9YQU77hOYlDNPLdvgmjceCFDKuDcFWAnM5aatZGHtZCwZAYboF5n/eMQu6+IastJ6ns4f2abg3DQkykIflO56XQ2LtZW7y8pNAiO5ttkYA4KZbcUUO1G7RK/qzH+tgaY/iE5ySbIuOFI145W02p8DEsJu/EPzRJlO1GcpBCO15cXBpJzkUko2sAdomN59stj5bhCB7ucCIRWFOz4CE3uiQAR51R4A/ZIL2jcIHalJskWV99XJVq9YuWq8HrFGMeiK1FyL+q1ycHmmXbWv81MZ/Y5Upf21s8NWyWIotLf+6HWFzs8oCnNwS2Xb/NXps9Y1OZDblQyMpnwSNT7cmitRjU3SGr1UFdpAEW56maSM6JfFtdCKs+xTtKfPmZUKw== damian.only@gmail.com" ];
```

2020-10-09 00:23 UTC, disassembler approved these changes

2020-10-09 00:23 UTC, merged